### ISSUE TITLE
Copy Dashboard is not working properly

### ISSUE THREAD

**Issue by kreinhar** [SoftwareAG/cumulocity-asset-properties-widget#28]
Hi Guys

just copied a dashboard from one Asset (which is a Group not a device) to another Group.
Result is that the widget shows the values of the former Asset and not the actual  Asset.

Assets are created with DTM.
![grafik](https://github.com/SoftwareAG/cumulocity-asset-properties-widget/assets/58287765/de8f871d-cbba-4ea6-8db7-8be2c9d7b01d)

**Comment by amar-c8y** [comment]
issue was fixed in latest release https://github.com/SoftwareAG/cumulocity-asset-properties-widget/releases/tag/sag-pkg-asset-properties-widget-1.0.1
